# Path to the folder where the fbx animations are stored
record_path: "D:\\MOCAP\\Recordings\\RecordingsUE\\"

# Name of actor that is being recorded (used for skeleton identification and take identification)
actor_name: "GlassesGuyRecord_C_2"
actor_name_shorthand: "GlassesGuyRecord"
# Name of the replay actor
replay_actor_name: "playLastActor"

# Websocket that controls the statemachine and we need to callback to
ws_url: "wss://signcollect.nl/unrealServer/"
# ws_url: "ws://192.168.0.180:8043/unrealServer"
export_endpoint: "https://signcollect.nl/fbx2glb/upload/"