# Path to the folder where the fbx animations are stored
# output_dir: "D:\\RecordingsUE\\"
output_dir: "D:\\MOCAP\\Recordings\\RecordingsUE\\"

# Name of actor that is being recorded (used for skeleton identification and take identification)
actor_name: "WitchRecord_C_1"
actor_name_shorthand: "WitchRecord"

# Name of the replay actor
replay_actor_name: "playLastActorWitch"

# ----------------------------------------------  #
# Clients and servers IP addresses and ports      #
# ----------------------------------------------  #
# Path flask server
pathServerAddr:  'localhost'
pathServerPort: 5001

# Websocket that controls the statemachine and we need to callback to
websocketServer: "wss://leffe.science.uva.nl:8043/unrealServer/"
# websocketServer: "ws://localhost:5012/"